# Change these first
owner: bipuldey19 # Your GitHub organization or username, where this repository lives
repo: pinger # The name of this repository

sites:
  - name: Open Subtitles API
    url: https://opensubtitles.bymirrorx.eu.org/
  - name: Spotify Downloader Bot
    url: https://88d7bda9-53a1-4177-bf79-731828afe6fb-00-w2e408mi083r.pike.replit.dev/
  - name: Ad-Free Embedded Video Player API
    url: https://videoadblocker.glitch.me/
  - name: Sports Stream Bot
    url: https://stream-mirrorx.glitch.me/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /pinger
  logoUrl: https://drive.google.com/uc?id=1YqD6qORGBGsS8t4Q8ep08NbWxHMPJhZk
  favicon: https://drive.google.com/uc?id=1YqD6qORGBGsS8t4Q8ep08NbWxHMPJhZk
  faviconSvg: https://drive.google.com/uc?id=1YqD6qORGBGsS8t4Q8ep08NbWxHMPJhZk
  theme: night
  name: MirrorX Pinger
  introTitle: "**MirrorX** Service Status Hub"
  introMessage: Stay informed about the availability and uptime of our bots and APIs with our Service Status Hub. Real-time updates and historical data to ensure your operations run smoothly.
  navbar:
    #- title: Status
    #  href: /
    #- title: GitHub
    #  href: https://github.com/bipuldey19/pinger

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
